//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mocassin.UI.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mocassin.UI.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ViewFormat_Json ähnelt.
        /// </summary>
        public static string DataObjectFormatKey_ViewFormat_Json {
            get {
                return ResourceManager.GetString("DataObjectFormatKey_ViewFormat_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ViewFormat_Tree ähnelt.
        /// </summary>
        public static string DataObjectFormatKey_ViewFormat_Tree {
            get {
                return ResourceManager.GetString("DataObjectFormatKey_ViewFormat_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ViewFormat_Xml ähnelt.
        /// </summary>
        public static string DataObjectFormatKey_ViewFormat_Xml {
            get {
                return ResourceManager.GetString("DataObjectFormatKey_ViewFormat_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cell.Boundaries ähnelt.
        /// </summary>
        public static string DisplayName_ModelViewport_CellFrameLayer {
            get {
                return ResourceManager.GetString("DisplayName_ModelViewport_CellFrameLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mocassin.Project.Settings.Global.xml ähnelt.
        /// </summary>
        public static string Filename_Project_Default_Configuration {
            get {
                return ResourceManager.GetString("Filename_Project_Default_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mocassin.Symmetry.db ähnelt.
        /// </summary>
        public static string Filename_Symmetry_Default_Database {
            get {
                return ResourceManager.GetString("Filename_Symmetry_Default_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die %USERPROFILE%/Documents/Mocassin/ ähnelt.
        /// </summary>
        public static string Folder_Userprofile_Resources {
            get {
                return ResourceManager.GetString("Folder_Userprofile_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mocassin_Logo_Round {
            get {
                object obj = ResourceManager.GetObject("Mocassin_Logo_Round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Render_MeshQuality ähnelt.
        /// </summary>
        public static string ResourceKey_ModelObject_MeshQuality {
            get {
                return ResourceManager.GetString("ResourceKey_ModelObject_MeshQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Render_Color ähnelt.
        /// </summary>
        public static string ResourceKey_ModelObject_RenderColor {
            get {
                return ResourceManager.GetString("ResourceKey_ModelObject_RenderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Render_Scaling ähnelt.
        /// </summary>
        public static string ResourceKey_ModelObject_RenderScaling {
            get {
                return ResourceManager.GetString("ResourceKey_ModelObject_RenderScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Render_Visibility_Flag ähnelt.
        /// </summary>
        public static string ResourceKey_ModelObject_RenderVisibilityFlag {
            get {
                return ResourceManager.GetString("ResourceKey_ModelObject_RenderVisibilityFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Model_Viewport_Render_Area ähnelt.
        /// </summary>
        public static string ResourceKey_ModelViewport_RenderArea {
            get {
                return ResourceManager.GetString("ResourceKey_ModelViewport_RenderArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] Symmetry_Database_Default {
            get {
                object obj = ResourceManager.GetObject("Symmetry_Database_Default", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3D Viewer - Error ähnelt.
        /// </summary>
        public static string Viewer3D_Error_Box_Caption {
            get {
                return ResourceManager.GetString("Viewer3D_Error_Box_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An exception occured during generation of the 3D model. This is most likley caused by ill defined geometry in one or more of the data sources. ähnelt.
        /// </summary>
        public static string Viewer3D_Error_Visual_Generation {
            get {
                return ResourceManager.GetString("Viewer3D_Error_Visual_Generation", resourceCulture);
            }
        }
    }
}
