//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mocassin.UI.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mocassin.UI.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewFormat_Json.
        /// </summary>
        public static string DataObjectFormatKey_ViewFormat_Json {
            get {
                return ResourceManager.GetString("DataObjectFormatKey_ViewFormat_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewFormat_Tree.
        /// </summary>
        public static string DataObjectFormatKey_ViewFormat_Tree {
            get {
                return ResourceManager.GetString("DataObjectFormatKey_ViewFormat_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewFormat_Xml.
        /// </summary>
        public static string DataObjectFormatKey_ViewFormat_Xml {
            get {
                return ResourceManager.GetString("DataObjectFormatKey_ViewFormat_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.Boundaries.
        /// </summary>
        public static string DisplayName_ModelViewport_CellFrameLayer {
            get {
                return ResourceManager.GetString("DisplayName_ModelViewport_CellFrameLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mocassin - Uncaught Exception.
        /// </summary>
        public static string Error_Uncaught_Exception_Caption {
            get {
                return ResourceManager.GetString("Error_Uncaught_Exception_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occured during execution of the program, the application will log the error and terminate..
        /// </summary>
        public static string Error_Uncaught_Exception_Message {
            get {
                return ResourceManager.GetString("Error_Uncaught_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mocassin.Project.Settings.Global.xml.
        /// </summary>
        public static string Filename_Project_Default_Configuration {
            get {
                return ResourceManager.GetString("Filename_Project_Default_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mocassin.Symmetry.db.
        /// </summary>
        public static string Filename_Symmetry_Default_Database {
            get {
                return ResourceManager.GetString("Filename_Symmetry_Default_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %USERPROFILE%/Documents/Mocassin/.
        /// </summary>
        public static string Folder_Userprofile_Resources {
            get {
                return ResourceManager.GetString("Folder_Userprofile_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mocassin_Logo_Round {
            get {
                object obj = ResourceManager.GetObject("Mocassin_Logo_Round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render_MeshQuality.
        /// </summary>
        public static string ResourceKey_ModelObject_MeshQuality {
            get {
                return ResourceManager.GetString("ResourceKey_ModelObject_MeshQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render_Color.
        /// </summary>
        public static string ResourceKey_ModelObject_RenderColor {
            get {
                return ResourceManager.GetString("ResourceKey_ModelObject_RenderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render_Display_Name.
        /// </summary>
        public static string ResourceKey_ModelObject_RenderDisplayName {
            get {
                return ResourceManager.GetString("ResourceKey_ModelObject_RenderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render_Inactive_Flag.
        /// </summary>
        public static string ResourceKey_ModelObject_RenderInactiveFlag {
            get {
                return ResourceManager.GetString("ResourceKey_ModelObject_RenderInactiveFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render_Material.
        /// </summary>
        public static string ResourceKey_ModelObject_RenderMaterial {
            get {
                return ResourceManager.GetString("ResourceKey_ModelObject_RenderMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render_Scaling.
        /// </summary>
        public static string ResourceKey_ModelObject_RenderScaling {
            get {
                return ResourceManager.GetString("ResourceKey_ModelObject_RenderScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render_Visibility_Flag.
        /// </summary>
        public static string ResourceKey_ModelObject_RenderVisibilityFlag {
            get {
                return ResourceManager.GetString("ResourceKey_ModelObject_RenderVisibilityFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model_Viewport_Render_Area.
        /// </summary>
        public static string ResourceKey_ModelViewport_RenderArea {
            get {
                return ResourceManager.GetString("ResourceKey_ModelViewport_RenderArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Symmetry_Database_Default {
            get {
                object obj = ResourceManager.GetObject("Symmetry_Database_Default", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Viewer - Error.
        /// </summary>
        public static string Viewer3D_Error_Box_Caption {
            get {
                return ResourceManager.GetString("Viewer3D_Error_Box_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured during generation of the 3D model. This is most likley caused by ill defined geometry in one or more of the data sources..
        /// </summary>
        public static string Viewer3D_Error_Visual_Generation {
            get {
                return ResourceManager.GetString("Viewer3D_Error_Visual_Generation", resourceCulture);
            }
        }
    }
}
