//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mocassin.UI.GUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double Limit_Render_MeshQuality_Upper {
            get {
                return ((double)(this["Limit_Render_MeshQuality_Upper"]));
            }
            set {
                this["Limit_Render_MeshQuality_Upper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double Limit_Render_MeshQuality_Lower {
            get {
                return ((double)(this["Limit_Render_MeshQuality_Lower"]));
            }
            set {
                this["Limit_Render_MeshQuality_Lower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double Default_Render_Mesh_Quality {
            get {
                return ((double)(this["Default_Render_Mesh_Quality"]));
            }
            set {
                this["Default_Render_Mesh_Quality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double Default_Render_Arrow_Scaling {
            get {
                return ((double)(this["Default_Render_Arrow_Scaling"]));
            }
            set {
                this["Default_Render_Arrow_Scaling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double Default_Render_Sphere_Scaling {
            get {
                return ((double)(this["Default_Render_Sphere_Scaling"]));
            }
            set {
                this["Default_Render_Sphere_Scaling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double Default_Render_Cube_Scaling {
            get {
                return ((double)(this["Default_Render_Cube_Scaling"]));
            }
            set {
                this["Default_Render_Cube_Scaling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double Default_Render_Mesh_Scaling {
            get {
                return ((double)(this["Default_Render_Mesh_Scaling"]));
            }
            set {
                this["Default_Render_Mesh_Scaling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Default_Render_Sphere_ThetaDiv {
            get {
                return ((int)(this["Default_Render_Sphere_ThetaDiv"]));
            }
            set {
                this["Default_Render_Sphere_ThetaDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int Default_Render_Sphere_PhiDiv {
            get {
                return ((int)(this["Default_Render_Sphere_PhiDiv"]));
            }
            set {
                this["Default_Render_Sphere_PhiDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Default_Render_Arrow_ThetaDiv {
            get {
                return ((int)(this["Default_Render_Arrow_ThetaDiv"]));
            }
            set {
                this["Default_Render_Arrow_ThetaDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public double Default_Render_Arrow_HeadLength {
            get {
                return ((double)(this["Default_Render_Arrow_HeadLength"]));
            }
            set {
                this["Default_Render_Arrow_HeadLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public byte Default_Render_UnstablePosition_Alpha {
            get {
                return ((byte)(this["Default_Render_UnstablePosition_Alpha"]));
            }
            set {
                this["Default_Render_UnstablePosition_Alpha"] = value;
            }
        }
    }
}
